### ISSUE TITLE
Add support for iOS Safari?

### ISSUE THREAD

**Issue by marcoscaceres** [litixsoft/karma-detect-browsers#12]
I've got the iOS simulator also running: 
https://www.npmjs.com/package/karma-ios-simulator-launcher

Worth integrating?

**Comment by 4kochi** [comment]
Sound great. I will check it out.

**Comment by 4kochi** [comment]
I have pushed a new branch `mobile_safari` for testing. The iOS Simulator seems a bit flaky. I often starts after the second retry. And when the simulator is already open, the are always some error message which i have to click away and the test run takes a lot of time. So i am not sure if it is the best use case to include it, since all Mac OS X user will be affected. 

Maybe you can check what might be the problem. You can run `npm test` in this branch which starts multiple karma runs at once.

**Comment by marcoscaceres** [comment]
Yeah, it's a bit hacky because there is limited IPC feedback from the simulator (e.g., I just wait 5 seconds in the hope that Safari opened). I'll fiddle around a bit more and see if I can get it more stable with karma-detect-browsers... maybe there is some means to get it to spit out more info that I can pipe through node.

**Comment by marcoscaceres** [comment]
(not much I can do right now unless Apple provides better feedback from IPC channel, so closing)
