### ISSUE TITLE
phantomjs tar.bz2 downloads by default

### ISSUE THREAD

**Issue by braydonf** [litixsoft/karma-detect-browsers#5]
When `usePhantomJS` option is set to `false`, the 13MB tar download for phantomjs isn't needed, and could be skipped. Is there a way to configure this dependency?

**Comment by 4kochi** [comment]
Ok, i can understand this. We are currently using peerDependencies in npm, so that all karma browser plugins are installed by npm. This is just convenient for the user. But in npm@v3 this behavior is subject to change. It seems like the peerDependencies will not be downloaded automatically any more. In this case you have to add the karma browser plugins in the `package.json` file of your project yourself.

So, long words short. Since the peerDependencies is changing in the future, we will release a new version of karma-detect-browsers which has no peerDependencies. So you have the full control which is downloaded.

**Comment by 4kochi** [comment]
New version 2.0 published. Now you can add the karma browser plugins yourself in the `package.json` of your project.
